hFB wconstant $C_varEnd
hFB wconstant $C_rsTop
hE5 wconstant $C_rsBot
hE5 wconstant $C_stTop
hE4 wconstant $C_this
hCD wconstant $C_stBot
hCC wconstant $C_treg6
hCB wconstant $C_treg5
hCA wconstant $C_treg4
hC9 wconstant $C_treg3
hC9 wconstant $C_cogdata
hC8 wconstant $C_stTOS
hC7 wconstant $C_rsPtr
hC6 wconstant $C_stPtr
hC5 wconstant $C_resetDreg
hC4 wconstant $C_fLongMask
hC3 wconstant $C_fAddrMask
hC2 wconstant $C_fCondMask
hC1 wconstant $C_fDestInc
hC0 wconstant $C_a_rsPop_ret
hBF wconstant $C_a_rsPop1
hBA wconstant $C_a_rsPop
hB9 wconstant $C_a_stpopC_treg_ret
hB9 wconstant $C_a_stPop_ret
hB8 wconstant $C_a_stPop1
hB3 wconstant $C_a_stPop
hB2 wconstant $C_a_stpopC_treg
hB1 wconstant $C_a_rsPush_ret
hAF wconstant $C_a_rsPush1
hAB wconstant $C_a_rsPush
hAA wconstant $C_a_stPush_ret
hA8 wconstant $C_a_stPush1
hA4 wconstant $C_a_stPush
hA1 wconstant $C_a_lasterr
hA0 wconstant $C_a_reset
h9C wconstant $C_a_0branch
h91 wconstant $C_a_(+loop)
h8F wconstant $C_a_(loop)
h8B wconstant $C_a_>r
h88 wconstant $C_a_2>r
h84 wconstant $C_a_r>
h81 wconstant $C_a__maskoutlo
h80 wconstant $C_a__maskouthi
h7D wconstant $C_a__maskin
h75 wconstant $C_a_next
h73 wconstant $C_a_exit
h71 wconstant $C_a_litw1
h6F wconstant $C_a_litw
h69 wconstant $C_a_litl
h64 wconstant $C_a_doconl
h61 wconstant $C_a_dovarw
h5F wconstant $C_a_dovarl
h5C wconstant $C_a_doconw
h58 wconstant $C_a_branch
h54 wconstant $C_a_COG!
h4F wconstant $C_a_ST!
h49 wconstant $C_a_RS!
h45 wconstant $C_a_COGat
h40 wconstant $C_a_STat
h3A wconstant $C_a_RSat
h38 wconstant $C_a_drop
h33 wconstant $C_a__xasm2>0
h2E wconstant $C_a__xasm1>1
h28 wconstant $C_a__xasm2>1
h25 wconstant $C_a__xasm2>1IMM
h16 wconstant $C_a__xasm2>flag
h13 wconstant $C_a__xasm2>flagIMM
h3 wconstant $C_a_lxasm
h2 wconstant $C_IP
h1 wconstant $C_treg2
h0 wconstant $C_treg1


