\ pin 0 - 16 - wave simulation
\ pin 17 - bit clock for i2s (32 * LR ) - this is generated by a counter, and the i2s driver synch to this clock
\ pin 18 - i2s LR ( left right signal)
\ pin 19 - data for i2s
\ pin 20 - pwm signal left channel  - 10 bit pwm
\ pin 21 - pwm right channel        - 10 bit pwm

\ dataOut  - low 16 its are left channel, high 16 bits are right channel
\ dataAck - 0 when the i2s driver is ready for data

\ cog 0 - i2s driver
\ cog 1 - left channel pwm
\ cog 2 - right channel pwm
\ cog 3 - tone generator
\ cog 4 - wave simulation driver

\ _i2s ( clockMask lrMask dataOutMask dataAddr ackAddr -- )


variable  dataOut
wvariable dataAck
wvariable simAddr

\
\ ( -- t/f) if the esc key or CTL-E has been hit
[ifndef esc?
: esc?
	fkey?
	if 
		dup h1B = swap 5 = or 
	else 
		drop 0 
	then
	;
]

\ _i2s ( clockMask lrMask dataOutMask dataAddr ackAddr -- )
lockdict create _i2s forthentry
$C_a_lxasm w, h13B  hFC  1- tuck - h9 lshift swap h1FF and or here W@ alignl h10 lshift or l,
hA0BE64C8 l, h5CFD72B3 l, hA0BE66C8 l, h5CFD72B3 l, hA0BE68C8 l, h5CFD72B3 l, hA0BE6AC8 l, h5CFD72B3 l,
hA0BE6CC8 l, h5CFD72B3 l, h64BFE934 l, h64BFE935 l, h8BE6F33 l, h5CFE752D l, h43E7132 l, h5CFE752D l,
h5CFE752D l, h5CFE752D l, h5CFE752D l, h5CFE752D l, h5CFE752D l, h5CFE752D l, h5CFE752D l, h5CFE752D l,
h5CFE752D l, h5CFE752D l, h5CFE752D l, h5CFE752D l, h5CFE752D l, h5CFE752D l, h68BFE935 l, h5CFE752D l,
h5CFE752D l, h5CFE752D l, h5CFE752D l, h5CFE752D l, h5CFE752D l, h5CFE752D l, h5CFE752D l, h5CFE752D l,
h5CFE752D l, h5CFE752D l, h5CFE752D l, h5CFE752D l, h5CFE752D l, h5CFE752D l, h5CFE752D l, h64BFE935 l,
h5C7C0108 l, hF03E6D36 l, hF43E6D36 l, h2DFE6E01 l, h70BFE934 l, h5C3C013A l, 0 l, 0 l,
h4 l, h2 l, h1 l, 0 l, 0 l, hFFFF7FFE l, 0 l,
freedict


\ ( addr period --  ) pwm from addr
lockdict create __pwmout forthentry
$C_a_lxasm w, h10C  hFC  1- tuck - h9 lshift swap h1FF and or here W@ alignl h10 lshift or l,
hA0BE14C8 l, h5CFD72B3 l, hA0BE16C8 l, h5CFD72B3 l, hA0BE13F1 l, h80BE130A l, h4BE110B l, h2CFE1006 l,
hF8BE130A l, hA4BFF908 l, h5C7C0102 l, h5C7C0073 l, 0 l, 0 l, 0 l, 0 l,

\ 1000 hz, left sin wave right sawtooth
\ ( output -- )
lockdict create __genwave forthentry
$C_a_lxasm w, h141  hFC  1- tuck - h9 lshift swap h1FF and or here W@ alignl h10 lshift or l,
hA0BE80C8 l, h5CFD72B3 l, hA0BE7BF1 l, h80BE7B3E l, hF8BE7B3E l, hA0BE553B l, h80BE773C l, h28FE5413 l,
hA0BE572A l, h5CFE3512 l, h28FE5401 l, h60BE552E l, hA0BE592A l, hA0BE552B l, h5CFE4B23 l, h28FE5401 l,
h60BE552E l, h2CFE5410 l, h68BE592A l, h83E5940 l, h5C7C0100 l, h5C7C0073 l, h613E5531 l, h623E5532 l,
hA4B2552A l, h68BE5533 l, h2CFE5401 l, h4BE552A l, hA496552A l, h80BE5537 l, h5C7C0000 l, h613E5531 l,
h623E5532 l, hA4B2552A l, h60BE5535 l, h2CFE5405 l, hA496552A l, h80BE5537 l, h5C7C0000 l, h60BE5534 l,
h2CFE5404 l, h5C7C0000 l, h623E5532 l, hA0AA5536 l, hA0D65400 l, h5C7C0000 l, 0 l, 0 l,
0 l, 0 l, hFFFF l, hFFFF0000 l, 0 l, h800 l, h1000 l, h7000 l,
h1FFF l, h7FF l, h1FFFF l, h10000 l, 0 l, 0 l, 0 l, 0 l,
h5CE13BD l, 0 l, h716 l, 0 l, 0 l,
freedict

lockdict create __simWave forthentry
$C_a_lxasm w, h110  hFC  1- tuck - h9 lshift swap h1FF and or here W@ alignl h10 lshift or l,
hA0BE16C8 l, h5CFD72B3 l, h4BE190B l, h4BE1D0C l, h80FE1C80 l, h28FE1C0C l, h60FE1C0F l, hA0FE1A01 l,
h2CBE1B0E l, hA0BE19F4 l, h60BE190F l, h68BE190D l, hA0BFE90D l, h5C7C00FE l, h5C7C0073 l, 0 l,
0 l, 0 l, 0 l, hFFFF0000 l,
freedict

c" d17 pinout d18 pinout d19 pinout 0 44100 lrToBitFreq setHza d17 >m  d18 >m d19 >m dataOut dataAck _i2s" 0 cogx

c" d20 pinout b00100 d26 lshift d20 or ctra COG! 1 frqa COG! dataOut d1024 __pwmout" 1 cogx

c" d21 pinout b00100 d26 lshift d21 or ctra COG! 1 frqa COG! dataOut 2 + d1024 __pwmout" 2 cogx

c" dataOut __genwave" 3 cogx

c" dira COG@ hFFFF or dira COG! simAddr __simWave" 4 cogx


: sr dataOut 2 + simAddr W! ;
: sl dataOut simAddr W! ;

sl
















lockdict create _i2s forthentry
$C_a_lxasm w, h13B  hFC  1- tuck - h9 lshift swap h1FF and or here W@ alignl h10 lshift or l,
hA0BE64C8 l, h5CFD72B3 l, hA0BE66C8 l, h5CFD72B3 l, hA0BE68C8 l, h5CFD72B3 l, hA0BE6AC8 l, h5CFD72B3 l,
hA0BE6CC8 l, h5CFD72B3 l, h64BFE934 l, h64BFE935 l, h8BE6F33 l, h5CFE752D l, h43E7132 l, h5CFE752D l,
h5CFE752D l, h5CFE752D l, h5CFE752D l, h5CFE752D l, h5CFE752D l, h5CFE752D l, h5CFE752D l, h5CFE752D l,
h5CFE752D l, h5CFE752D l, h5CFE752D l, h5CFE752D l, h5CFE752D l, h5CFE752D l, h68BFE935 l, h5CFE752D l,
h5CFE752D l, h5CFE752D l, h5CFE752D l, h5CFE752D l, h5CFE752D l, h5CFE752D l, h5CFE752D l, h5CFE752D l,
h5CFE752D l, h5CFE752D l, h5CFE752D l, h5CFE752D l, h5CFE752D l, h5CFE752D l, h5CFE752D l, h64BFE935 l,
h5C7C0108 l, hF03E6D36 l, hF43E6D36 l, h2DFE6E01 l, h70BFE934 l, h5C3C013A l, 0 l, 0 l,
h4 l, h2 l, h1 l, 0 l, 0 l, hFFFF7FFE l, 0 l,
freedict

0 d!



h7EFF7FEF d!
hA555A555 d!
h800010005 d!
0 d!









\ assembler source

\ _i2s ( clockMask lrMask dataOutMask dataAddr ackAddr -- )
build_BootOpt :rasm
	            mov	    __ackAddr , $C_stTOS
	            spop
	            mov     __dataAddr , $C_stTOS
	            spop
	            mov     __dataOutMask , $C_stTOS
	            spop
	            mov     __lrMask , $C_stTOS
	            spop
	            mov     __clockMask , $C_stTOS
                spop
                andn    outa , __dataOutMask
                andn    outa , __lrMask
__mainLoop
                rdlong  __currentData , __dataAddr
\ clock - 49
                jmpret  __bitOutRet , # __bitOut
\ max t = 55 clocks
                wrword  __zero , __ackAddr
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut

                or      outa , __lrMask

                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                andn    outa , __lrMask
\ clock - 22
                jmp     # __mainLoop
\ clock - 26

__bitOut
                waitpeq __clockMask , __clockMask
\ clock - 0 -- clock 55
                waitpne __clockMask , __clockMask
\ clock - 6
                shl     __currentData , # 1 wc
\ clock - 10
                muxc    outa , __dataOutMask
\ clock - 14
                jmp     __bitOutRet
\ clock - 18    

__ackAddr
                0
__dataAddr
                0
__dataOutMask
                4
__lrMask
                2
__clockMask
                1
__currentData
                0
__zero
                0
__data
                hFFFF7FFE
__bitOutRet
                0

;asm _i2s


\ ( addr period --  ) pwm from addr
build_BootOpt :rasm
                mov     __period , $C_stTOS
                spop
                mov     __addr , $C_stTOS
                spop
                mov     __time , cnt
                add     __time , __period
__mainLoop
                rdword  __value , __addr
                shl     __value , # 6
                waitcnt __time , __period
                neg     phsa , __value
                jmp     # __mainLoop
                jexit
__value
                0                
__time
                0
__period
                0
__addr
                0
;asm __pwmout



\ 1000 hz, left sin wave right sawtooth
\ ( output -- )
build_BootOpt :rasm
                mov     __output , $C_stTOS
                spop
                mov     __time , cnt
                add     __time , __period
__mainLoop
                waitcnt __time , __period
                mov     __r0 , __currIndex
                add     __currIndex , __step
                shr     __r0 , # d19
                mov     __r1 , __r0

                jmpret  __sinRet ,  # __sin
                shr     __r0 , # 1
                and     __r0 , __lomask
                mov     __r2 , __r0

                mov     __r0 , __r1
                jmpret  __sawRet ,  # __saw
                shr     __r0 , # 1
                and     __r0 , __lomask
                shl     __r0 , # d16
                or      __r2 , __r0
                wrlong  __r2 , __output
                jmp     # __mainLoop
                jexit
__sin
                test    __r0 , __quad90 wc
                test    __r0 , __quad180 wz
    if_c        neg     __r0 , __r0
                or      __r0 , __sinTable
                shl     __r0 , # 1
                rdword  __r0 , __r0
    if_nz       neg     __r0 , __r0
                add     __r0 , __midValue
__sinRet
                ret
__triangle
                test    __r0 , __quad90 wc
                test    __r0 , __quad180 wz
    if_c        neg     __r0 , __r0
                and     __r0 , __angleMask
                shl     __r0 , # 5
    if_nz       neg     __r0 , __r0
                add     __r0 , __midValue
__triangleRet
                ret
__saw
                and     __r0 , __angleMask360
                shl     __r0 , # 4
__sawRet
                ret
__square
                test    __r0 , __quad180 wz
    if_z        mov     __r0 , __maxValue
    if_nz       mov     __r0 , # 0
__squareRet
                ret
__r0
                0
__r1
                0
__r2
                0
__r3
                0
__lomask
                hFFFF
__himask
                hFFFF0000
__type
                0
__quad90
                h800 
__quad180
                h1000 
\ 0xE000 >> 1
__sinTable
                h7000
__angleMask360
                h1FFF
__angleMask
                h7FF
__maxValue
                h1FFFF 
__midValue
                h10000
__debug
                0
__output
                0
__att 
                0
__currIndex
                0
__step
                d97391549
__time
                0
__period
                d1814
__debug
                0
__output
                0
;asm __genwave


\ ( addrOfAddr --  ) 
build_BootOpt :rasm
                mov     __addrOfAddr , $C_stTOS
                spop
__mainLoop
                rdword  __r0 , __addrOfAddr
                rdword  __value , __r0
                add     __value , # h80
                shr     __value , # d12
                and     __value , # d15
                mov     __r1 , # 1
                shl     __r1 , __value
                mov     __r0 , outa
                and     __r0 , __himask 
                or      __r0 , __r1
                mov     outa , __r1
                jmp     # __mainLoop
                jexit
__addrOfAddr
                0
__r0
                0            
__r1
                0            
__value
                0            
__himask
                hFFFF0000
;asm __simWave





















































: up 
    0 dataOut L!
    7 pinout
    begin
        dataOut L@
        h00010001 +
        begin
            dataAck W@ 0 =
        until
        7 pinlo
        dataOut L!
        1 dataAck W!
        esc?  
        7 pinhi  
    until 
    ;
: lrToBitFreq 
    32 * 
    ;
: showFreq
    lrToBitFreq dup dup cr
    c"     BIT freq: " .cstr . cr
    32 u/
    c"      LR freq: " .cstr . cr 
    clkfreq swap u/
    c" # cpu clocks: " .cstr . cr 
    ; 

\ ( angle type -- res ) angle 0x2000 is 2PI or 360 degrees, 
\   type 0 sin, 1 triangle, 2 square, 3 sawtooth, res has 17 significant bits from 0 - h1FFFF
build_BootOpt :rasm
                mov     __type , $C_stTOS
                spop
                mov     __r0 , $C_stTOS
                cmp     __type , # 3                  wc wz
    if_e        jmpret  __sawRet , # __saw
                cmp     __type , # 2                  wc wz
    if_e        jmpret  __squareRet , # __square
                cmp     __type , # 1                  wc wz
    if_e        jmpret  __triangleRet , # __triangle
                cmp    __type , # 0                   wc wz
    if_e        jmpret  __sinRet ,  # __sin
                mov     $C_stTOS , __r0
                jexit
 
__sin
                test    __r0 , __quad90 wc
                test    __r0 , __quad180 wz
    if_c        neg     __r0 , __r0
                or      __r0 , __sinTable
                shl     __r0 , # 1
                rdword  __r0 , __r0
    if_nz       neg     __r0 , __r0
                add     __r0 , __midValue
__sinRet
                ret

__triangle
                test    __r0 , __quad90 wc
                test    __r0 , __quad180 wz
    if_c        neg     __r0 , __r0
                and     __r0 , __angleMask
                shl     __r0 , # 5
    if_nz       neg     __r0 , __r0
                add     __r0 , __midValue
__triangleRet
                ret

__saw
                and     __r0 , __angleMask360
                shl     __r0 , # 4
__sawRet
                ret

__square
                test    __r0 , __quad180 wz
    if_z        mov     __r0 , __maxValue
    if_nz       mov     __r0 , # 0
__squareRet
                ret

__r0
                0
__type
                0
__quad90
                h800 
__quad180
                h1000 
\ 0xE000 >> 1
__sinTable
                h7000
__angleMask360
                h1FFF
__angleMask
                h7FF
__maxValue
                h1FFFF 
__midValue
                h10000
;asm wave






\ ( curr -- curr idx sin)
build_BootOpt :rasm
                mov     __currIndex , $C_stTOS
                mov     __r0 , __currIndex
                add     __currIndex , __step
                mov     $C_stTOS , __currIndex
                spush                
                shr     __r0 , # d19
                mov     $C_stTOS , __r0
                spush
                jmpret  __sinRet ,  # __sin
                shr     __r0 , # 1
                mov     $C_stTOS , __r0
                jexit
__sin
                test    __r0 , __quad90 wc
                test    __r0 , __quad180 wz
    if_c        neg     __r0 , __r0
                or      __r0 , __sinTable
                shl     __r0 , # 1
                rdword  __r0 , __r0
    if_nz       neg     __r0 , __r0
                add     __r0 , __midValue
__sinRet
                ret
__triangle
                test    __r0 , __quad90 wc
                test    __r0 , __quad180 wz
    if_c        neg     __r0 , __r0
                and     __r0 , __angleMask
                shl     __r0 , # 5
    if_nz       neg     __r0 , __r0
                add     __r0 , __midValue
__triangleRet
                ret
__saw
                and     __r0 , __angleMask360
                shl     __r0 , # 4
__sawRet
                ret
__square
                test    __r0 , __quad180 wz
    if_z        mov     __r0 , __maxValue
    if_nz       mov     __r0 , # 0
__squareRet
                ret
__r0
                0
__type
                0
__quad90
                h800 
__quad180
                h1000 
\ 0xE000 >> 1
__sinTable
                h7000
__angleMask360
                h1FFF
__angleMask
                h7FF
__maxValue
                h1FFFF 
__midValue
                h10000
__debug
                0
__output
                0
__att 
                0
__currIndex
                0
__step
                d97391549
__time
                0
__period
                d1814
__debug
                0
__output
                0
;asm __genwave2





variable __pwmValue

\ ( addr -- )
: pwmout 
    0 pinout 1 pinout
    b00100 d26 lshift ctra COG!
    1 frqa COG!
    __pwmValue d1024 __pwmout ;

: v __pwmValue L! ;

c" __pwmValue pwmout" 0 cogx


900 v




: wout h100 + d13 rshift >m  outa COG@ hFFFF0000 and or outa COG! ;


lockdict create wave forthentry
$C_a_lxasm w, h127  hFC  1- tuck - h9 lshift swap h1FF and or here W@ alignl h10 lshift or l,
hA0BE3EC8 l, h5CFD72B3 l, h877E3E03 l, h5CEA3518 l, h877E3E02 l, h5CEA3D1B l, h877E3E01 l, h5CEA2F10 l,
h877E3E00 l, h5CEA1F07 l, h5C7C0073 l, h613D9120 l, h623D9121 l, hA4B190C8 l, h68BD9122 l, h2CFD9001 l,
h4BD90C8 l, hA49590C8 l, h80BD9126 l, h5C7C0000 l, h613D9120 l, h623D9121 l, hA4B190C8 l, h60BD9124 l,
h2CFD9005 l, hA49590C8 l, h80BD9126 l, h5C7C0000 l, h60BD9123 l, h2CFD9004 l, h5C7C0000 l, h623D9121 l,
hA0A99125 l, hA0D59000 l, h5C7C0000 l, 0 l, h800 l, h1000 l, h7000 l, h1FFF l,
h7FF l, h1FFFF l, h10000 l,
freedict





: sin 0 wave ;
: triangle 1 wave ;
: square 2 wave ;
: sawtooth 3 wave ;

: winit dira COG@ hFFFF or dira COG! ;

: wout h100 + d13 rshift >m  outa COG@ hFFFF0000 and or outa COG! ;

: sinwave
    winit
    0 begin
        dup sin wout 
        h100 + 
        0 until
    drop
;


 

: tw
    h2100 0 do
        i . i 0 wave . i 1 wave . i 2 wave .  i 3 wave . cr
    loop
;

: tw1
    h80 0 do
        i . i 0 wave . i 1 wave . i 2 wave .  i 3 wave . cr
    loop
    cr cr cr cr
    h880 h780 do
        i . i 0 wave . i 1 wave . i 2 wave .  i 3 wave . cr
    loop
    cr cr cr cr
    h1040 hFC0 do
        i . i 0 wave . i 1 wave . i 2 wave .  i 3 wave . cr
    loop
    cr cr cr cr
    h1880 h1780 do
        i . i 0 wave . i 1 wave . i 2 wave .  i 3 wave . cr
    loop
    cr cr cr cr
    h2040 h1FC0 do
        i . i 0 wave . i 1 wave . i 2 wave .  i 3 wave . cr
    loop
;

: tw2
    0 begin
        dup 
        esc?
    until

;


: tt
    h2100 0 do
        i . i h1FFF and 4 lshift h10000 - . cr
    h100 +loop
;



//////////////////////////////////////////////////////////////////////////////////////////////////





lockdict create __genwave forthentry
$C_a_lxasm w, h13A  hFC  1- tuck - h9 lshift swap h1FF and or here W@ alignl h10 lshift or l,
hA0BE72C8 l, h5CFD72B3 l, hA0BE6DF1 l, h80BE6D37 l, hF8BE6D37 l, h6CFFE804 l, hA0BE4D34 l, h80BE6935 l,
h28FE4C13 l, hA0BE4F26 l, h5CFE2D0E l, h28FE4C01 l, h60BE4D28 l, h2CFE4E10 l, h68BE4F26 l, h83E4F39 l,
h5C7C0100 l, h5C7C0073 l, h613E4D2A l, h623E4D2B l, hA4B24D26 l, h68BE4D2C l, h2CFE4C01 l, h4BE4D26 l,
hA4964D26 l, h80BE4D30 l, h5C7C0000 l, h613E4D2A l, h623E4D2B l, hA4B24D26 l, h60BE4D2E l, h2CFE4C05 l,
hA4964D26 l, h80BE4D30 l, h5C7C0000 l, h60BE4D2D l, h2CFE4C04 l, h5C7C0000 l, h623E4D2B l, hA0AA4D2F l,
hA0D64C00 l, h5C7C0000 l, 0 l, 0 l, hFFFF l, 0 l, h800 l, h1000 l,
h7000 l, h1FFF l, h7FF l, h1FFFF l, h10000 l, 0 l, 0 l, 0 l,
0 l, h5CE13BD l, 0 l, h716 l, 0 l, 0 l,
freedict

variable tone1Out
variable tone1Debug


: esc? fkey? if dup h1B = swap 5 = or else drop 0 then ;

c" 2 pinout tone1Out __genwave" 1 cogx

: dw 
    0
    begin 
        tone1Out L@ dup 16 rshift . h2C emit hFFFF and . cr
        esc?
    until
    ;




0 pinout 1 pinout 2 pinout 3 pinout



lockdict create __pwmout forthentry
$C_a_lxasm w, h141  h131  1- tuck - h9 lshift swap h1FF and or here W@ alignl h10 lshift or l,
hA0BE7EC8 l, h5CFD72B3 l, hA0BE80C8 l, h5CFD72B3 l, hA0BE7DF1 l, h80BE7D3F l, h8BE7B40 l, hF8BE7D3F l,
hA4BFF93D l, h6CFFE802 l, h5C7C0137 l, h5C7C0073 l, 0 l, 0 l, 0 l, 0 l,
freedict

lockdict create __genwave forthentry
$C_a_lxasm w, h137  hFC  1- tuck - h9 lshift swap h1FF and or here W@ alignl h10 lshift or l,
hA0BE6AC8 l, h5CFD72B3 l, hA0BE6CC8 l, h5CFD72B3 l, hA0BE67F1 l, h80BE6734 l, hF8BE6734 l, h6CFFE804 l,
hA0BE4B31 l, h80BE6332 l, h28FE4A13 l, h83E4B35 l, h5CFE2B0D l, h28FE4A01 l, h83E4B36 l, h5C7C0102 l,
h5C7C0073 l, h613E4B27 l, h623E4B28 l, hA4B24B25 l, h68BE4B29 l, h2CFE4A01 l, h4BE4B25 l, hA4964B25 l,
h80BE4B2D l, h5C7C0000 l, h613E4B27 l, h623E4B28 l, hA4B24B25 l, h60BE4B2B l, h2CFE4A05 l, hA4964B25 l,
h80BE4B2D l, h5C7C0000 l, h60BE4B2A l, h2CFE4A04 l, h5C7C0000 l, h623E4B28 l, hA0AA4B2C l, hA0D64A00 l,
h5C7C0000 l, 0 l, 0 l, h800 l, h1000 l, h7000 l, h1FFF l, h7FF l,
h1FFFF l, h10000 l, 0 l, 0 l, 0 l, 0 l, h5CE13BD l, 0 l,
h716 l, 0 l, 0 l,
freedict

variable tone1Out
variable tone1Debug

: esc? fkey? if dup h1B = swap 5 = or else drop 0 then ;

: dw 
    begin 
        tone1Out L@ . tone1Debug L@ . cr
        esc?
    until
    ;

variable __pwmValue

\ ( addr -- )
: pwmout 
    0 pinout 1 pinout
    b00100 d26 lshift ctra COG!
    1 frqa COG!
    tone1Out d1024 __pwmout ;

c" tone1Out pwmout" 0 cogx
c" 2 pinout tone1Out tone1Debug __genwave" 1 cogx

dw





\ 13 bits
d8192 constant tableLen
d44100 constant sampleFreq
\ 32 bits - 13 bits = 19
d19 constant stepShift 

clkfreq 1024 / constant period


variable tone1Freq
variable tone1Step
variable tone1Index
variable tone1Att
variable toneType

variable tone1Out
variable tone1Debug

: freqToStep tableLen u* 1 stepShift lshift sampleFreq u*/ ;

\ ( att phase freq type -- ) att 0 - 256 , phase degrees, freq
: st1 toneType L! dup tone1Freq L! freqToStep tone1Step L!  360 /mod drop tableLen u* 360 / tone1Index L! tone1Att L! ;

: dt1 period . toneType L@ . tone1Freq L@ . tone1Step L@ . tone1Index L@ . tone1Att L@ . cr ;

\ ( period step phase att output -- )

: genWave period tone1Freq L@ freqToStep 0 256  tone1Out  __genwave ;

256 0 1000 0 st1

dt1



: dw 
    begin 
    tone1Out L@ . cr
    0 until
    ;











\ old stuff

\ _i2s ( clockMask lrMask dataOutMask dataAddr ackAddr -- )
build_BootOpt :rasm
	            mov	    __ackAddr , $C_stTOS
	            spop
	            mov     __dataAddr , $C_stTOS
	            spop
	            mov     __dataOutMask , $C_stTOS
	            spop
	            mov     __lrMask , $C_stTOS
	            spop
	            mov     __clockMask , $C_stTOS
                spop
                andn    outa , __dataOutMask
__mainLoop
                andn    outa , __lrMask
                jmpret  __bitOutRet , # __bitOut        
                rdlong  __currentData , __dataAddr
\ clock - 41
                jmpret  __bitOutRet , # __bitOut
\ clock - 47 max
                wrword  __zero , __ackAddr
                jmpret  __bitOutRet , # __bitOut  
                jmpret  __bitOutRet , # __bitOut  
                jmpret  __bitOutRet , # __bitOut  
                jmpret  __bitOutRet , # __bitOut  
                jmpret  __bitOutRet , # __bitOut  
                jmpret  __bitOutRet , # __bitOut  
                jmpret  __bitOutRet , # __bitOut  
                jmpret  __bitOutRet , # __bitOut  
                jmpret  __bitOutRet , # __bitOut  
                jmpret  __bitOutRet , # __bitOut  
                jmpret  __bitOutRet , # __bitOut  
                jmpret  __bitOutRet , # __bitOut  
                jmpret  __bitOutRet , # __bitOut  
                jmpret  __bitOutRet , # __bitOut  
                or      outa , __lrMask
                jmpret  __bitOutRet , # __bitOut  
                jmpret  __bitOutRet , # __bitOut  
                jmpret  __bitOutRet , # __bitOut  
                jmpret  __bitOutRet , # __bitOut  
                jmpret  __bitOutRet , # __bitOut  
                jmpret  __bitOutRet , # __bitOut  
                jmpret  __bitOutRet , # __bitOut  
                jmpret  __bitOutRet , # __bitOut  
                jmpret  __bitOutRet , # __bitOut  
                jmpret  __bitOutRet , # __bitOut  
                jmpret  __bitOutRet , # __bitOut  
                jmpret  __bitOutRet , # __bitOut  
                jmpret  __bitOutRet , # __bitOut  
                jmpret  __bitOutRet , # __bitOut  
                jmpret  __bitOutRet , # __bitOut  
                jmpret  __bitOutRet , # __bitOut  
                jmp     # __mainLoop
__bitOut
\ 
                waitpeq __clockMask , __clockMask
\ clock - 0 -- clock 47
                waitpne __clockMask , __clockMask
\ clock - 6
                shl     __currentData , # 1 wc
\ clock - 10
                muxc    outa , __dataOutMask
\ clock - 14
                jmp     __bitOutRet
\ clock - 18    

__ackAddr
                0
__dataAddr
                0
__dataOutMask
                0
__lrMask
                0
__clockMask
                0
__currentData
                0
__bitOutRet
                0
__zero
                0
;asm _i2s




c" 0  1000 setHza" 4 cogx
c" i2s" 5 cogx
lac

: i2b dup h8000_0000 and 1 1 waitpeq 0 1 waitpeq if 1 pinhi else 1 pinlo then 1 lshift 1 1 waitpeq ;

\ i2s ( n -- )
: i2s 
    1 pinout 2 pinout 3 pinout
    begin
        2 pinlo
        i2b drop hFFFF7FFE i2b i2b i2b  i2b i2b i2b i2b   i2b i2b i2b i2b  i2b i2b i2b i2b 
        2 pinhi
        i2b                i2b i2b i2b  i2b i2b i2b i2b   i2b i2b i2b i2b  i2b i2b i2b i2b
        3 pinhi
        key? if key 5 = else 0 then 
        3 pinlo
    until
    ;





: i2s 
    1 pinout 2 pinout 3 pinout
    begin
        2 pinlo
        i2b drop hFFFF7FFE i2b i2b i2b  i2b i2b i2b i2b   i2b i2b i2b i2b  i2b i2b i2b i2b 
        2 pinhi
        i2b                i2b i2b i2b  i2b i2b i2b i2b   i2b i2b i2b i2b  i2b i2b i2b i2b
        3 pinhi
        key? if key 5 = else 0 then 
        3 pinlo
    until
    ;





: cntToMs clkfreq 1000 u/ u/ ;
: si
    begin
        fkey?
        if
            h61 =
        else
            drop
            0
        then
    until
    cnt COG@
    0
    begin 
        5 delms
        fkey?
        if
            5 =
            swap 1 + swap
        else
            drop
            0
        then 
    until
    . cr
    cnt COG@ swap - cntToMs . cr
    ;


a
000 01234567890123456789012345678901234567890123456789012345678901234567890123456789
001 01234567890123456789012345678901234567890123456789012345678901234567890123456789
002 01234567890123456789012345678901234567890123456789012345678901234567890123456789
003 01234567890123456789012345678901234567890123456789012345678901234567890123456789
004 01234567890123456789012345678901234567890123456789012345678901234567890123456789
005 01234567890123456789012345678901234567890123456789012345678901234567890123456789
006 01234567890123456789012345678901234567890123456789012345678901234567890123456789
007 01234567890123456789012345678901234567890123456789012345678901234567890123456789
008 01234567890123456789012345678901234567890123456789012345678901234567890123456789
009 01234567890123456789012345678901234567890123456789012345678901234567890123456789
010 01234567890123456789012345678901234567890123456789012345678901234567890123456789
011 01234567890123456789012345678901234567890123456789012345678901234567890123456789
012 01234567890123456789012345678901234567890123456789012345678901234567890123456789
013 01234567890123456789012345678901234567890123456789012345678901234567890123456789
014 01234567890123456789012345678901234567890123456789012345678901234567890123456789
015 01234567890123456789012345678901234567890123456789012345678901234567890123456789
016 01234567890123456789012345678901234567890123456789012345678901234567890123456789
017 01234567890123456789012345678901234567890123456789012345678901234567890123456789
018 01234567890123456789012345678901234567890123456789012345678901234567890123456789
019 01234567890123456789012345678901234567890123456789012345678901234567890123456789
020 01234567890123456789012345678901234567890123456789012345678901234567890123456789
021 01234567890123456789012345678901234567890123456789012345678901234567890123456789
022 01234567890123456789012345678901234567890123456789012345678901234567890123456789
023 01234567890123456789012345678901234567890123456789012345678901234567890123456789
024 01234567890123456789012345678901234567890123456789012345678901234567890123456789
025 01234567890123456789012345678901234567890123456789012345678901234567890123456789
026 01234567890123456789012345678901234567890123456789012345678901234567890123456789
027 01234567890123456789012345678901234567890123456789012345678901234567890123456789
028 01234567890123456789012345678901234567890123456789012345678901234567890123456789
029 01234567890123456789012345678901234567890123456789012345678901234567890123456789
030 01234567890123456789012345678901234567890123456789012345678901234567890123456789
031 01234567890123456789012345678901234567890123456789012345678901234567890123456789
032 01234567890123456789012345678901234567890123456789012345678901234567890123456789
033 01234567890123456789012345678901234567890123456789012345678901234567890123456789
034 01234567890123456789012345678901234567890123456789012345678901234567890123456789
035 01234567890123456789012345678901234567890123456789012345678901234567890123456789
036 01234567890123456789012345678901234567890123456789012345678901234567890123456789
037 01234567890123456789012345678901234567890123456789012345678901234567890123456789
038 01234567890123456789012345678901234567890123456789012345678901234567890123456789
039 01234567890123456789012345678901234567890123456789012345678901234567890123456789
040 01234567890123456789012345678901234567890123456789012345678901234567890123456789
041 01234567890123456789012345678901234567890123456789012345678901234567890123456789
042 01234567890123456789012345678901234567890123456789012345678901234567890123456789
043 01234567890123456789012345678901234567890123456789012345678901234567890123456789
044 01234567890123456789012345678901234567890123456789012345678901234567890123456789
045 01234567890123456789012345678901234567890123456789012345678901234567890123456789
046 01234567890123456789012345678901234567890123456789012345678901234567890123456789
047 01234567890123456789012345678901234567890123456789012345678901234567890123456789
048 01234567890123456789012345678901234567890123456789012345678901234567890123456789
049 01234567890123456789012345678901234567890123456789012345678901234567890123456789
050 01234567890123456789012345678901234567890123456789012345678901234567890123456789
051 01234567890123456789012345678901234567890123456789012345678901234567890123456789
052 01234567890123456789012345678901234567890123456789012345678901234567890123456789
053 01234567890123456789012345678901234567890123456789012345678901234567890123456789
054 01234567890123456789012345678901234567890123456789012345678901234567890123456789
055 01234567890123456789012345678901234567890123456789012345678901234567890123456789
056 01234567890123456789012345678901234567890123456789012345678901234567890123456789
057 01234567890123456789012345678901234567890123456789012345678901234567890123456789
058 01234567890123456789012345678901234567890123456789012345678901234567890123456789
059 01234567890123456789012345678901234567890123456789012345678901234567890123456789
060 01234567890123456789012345678901234567890123456789012345678901234567890123456789
061 01234567890123456789012345678901234567890123456789012345678901234567890123456789
062 01234567890123456789012345678901234567890123456789012345678901234567890123456789
063 01234567890123456789012345678901234567890123456789012345678901234567890123456789
064 01234567890123456789012345678901234567890123456789012345678901234567890123456789
065 01234567890123456789012345678901234567890123456789012345678901234567890123456789
066 01234567890123456789012345678901234567890123456789012345678901234567890123456789
067 01234567890123456789012345678901234567890123456789012345678901234567890123456789
068 01234567890123456789012345678901234567890123456789012345678901234567890123456789
069 01234567890123456789012345678901234567890123456789012345678901234567890123456789
070 01234567890123456789012345678901234567890123456789012345678901234567890123456789
071 01234567890123456789012345678901234567890123456789012345678901234567890123456789
072 01234567890123456789012345678901234567890123456789012345678901234567890123456789
073 01234567890123456789012345678901234567890123456789012345678901234567890123456789
074 01234567890123456789012345678901234567890123456789012345678901234567890123456789
075 01234567890123456789012345678901234567890123456789012345678901234567890123456789
076 01234567890123456789012345678901234567890123456789012345678901234567890123456789
077 01234567890123456789012345678901234567890123456789012345678901234567890123456789
078 01234567890123456789012345678901234567890123456789012345678901234567890123456789
079 01234567890123456789012345678901234567890123456789012345678901234567890123456789
080 01234567890123456789012345678901234567890123456789012345678901234567890123456789
081 01234567890123456789012345678901234567890123456789012345678901234567890123456789
082 01234567890123456789012345678901234567890123456789012345678901234567890123456789
083 01234567890123456789012345678901234567890123456789012345678901234567890123456789
084 01234567890123456789012345678901234567890123456789012345678901234567890123456789
085 01234567890123456789012345678901234567890123456789012345678901234567890123456789
086 01234567890123456789012345678901234567890123456789012345678901234567890123456789
087 01234567890123456789012345678901234567890123456789012345678901234567890123456789
088 01234567890123456789012345678901234567890123456789012345678901234567890123456789
089 01234567890123456789012345678901234567890123456789012345678901234567890123456789
090 01234567890123456789012345678901234567890123456789012345678901234567890123456789
091 01234567890123456789012345678901234567890123456789012345678901234567890123456789
092 01234567890123456789012345678901234567890123456789012345678901234567890123456789
093 01234567890123456789012345678901234567890123456789012345678901234567890123456789
094 01234567890123456789012345678901234567890123456789012345678901234567890123456789
095 01234567890123456789012345678901234567890123456789012345678901234567890123456789
096 01234567890123456789012345678901234567890123456789012345678901234567890123456789
097 01234567890123456789012345678901234567890123456789012345678901234567890123456789
098 01234567890123456789012345678901234567890123456789012345678901234567890123456789
099 01234567890123456789012345678901234567890123456789012345678901234567890123456789



