\ CURRENT TESTING

\ pin0 - pin15 - simwave __toneOutput
\ pin 17 - bit clock for i2s (32 * LR ) - this is generated by a counter, and the i2s driver synch to this clock
\ pin 18 - i2s LR ( left right signal) 
\ pin 19 - data for i2s

\ cog 0 - i2s driver,  clock A produces the bit clk 44100 sample rate
\ cog 1 - wave generator, possibility for freq < 2 khz ??? generation at 22.5 kHz, 10 waves ???
\ cog 2 - wave generator
\ cog 3 - wave generator / wave display for lac
\ cog 4 - mixer 
\ cog 5 - tone / envelope driver
\ cog 6 - ui 
\ cog 7 - serial interface

d17 constant i2sBitClock
d18 constant i2sLrClock
d19 constant i2sData

\ 13 tableAddress bits for look up tables
d8192 constant tableLen

\ 32 bits - 13 bits = 19, shift when using a 32 bit unsigned value to index a table
d19 constant stepShift 

\ sample frequency
d44100 constant sampleFreq

\ clock cycles per sample
clkfreq sampleFreq / constant period

\ bit frequency for i2s
sampleFreq d32 * constant bitFrequency

\ (freq -- stepPerPeriod)
: freqToStep tableLen u* 1 stepShift lshift sampleFreq u*/ ;

\
\ ( -- t/f) if the esc key or CTL-E has been hit
[ifndef esc?
: esc?
	fkey?
	if 
		dup h1B = swap 5 = or 
	else 
		drop 0 
	then
	;
]

variable numTones 0 l, 0 l,
variable cyclesLeft 0 l, 0 l,
variable toneOutput 0 l, 0 l,
variable toneSum
variable volume

0 volume L!
0 toneSum L!
0 toneOutput L!

d15 constant maxNumTones
d256 constant maxVolume

5 numTones L!
5 numTones 4+ L!
5 numTones 4+ 4+ L!

\ set up for 15 tones, currently running at 5 tones per cog

d5 constant cogArraySize
variable tonesArray
0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 
0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l,
0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l,
tonesArray             constant typeGainVector
tonesArray     d60 +   constant stepVector
tonesArray     d120 +  constant currentStepIndexVector

0 constant typeSin
1 constant typeTriangle
2 constant typeSquare
3 constant typeSaw

: setNumTones
    maxNumTones 1+ min numTones L!
;

\ ( type gain freq index -- )
: setTone 
    maxNumTones min 4* swap freqToStep over stepVector + L! 
    currentStepIndexVector over + 0 swap L!
    rot d16 lshift rot or swap typeGainVector + L!
;

\ ( n -- ) n = 0-256 overall volume
: setVolume
    maxVolume min volume L!
;

\ _i2s ( clockMask lrMask dataOutMask dataAddr  -- )

lockdict create _i2s forthentry
$C_a_lxasm w, h136  hFC  1- tuck - h9 lshift swap h1FF and or here W@ alignl h10 lshift or l,
hA0BE5EC8 l, h5CFD72B3 l, hA0BE60C8 l, h5CFD72B3 l, hA0BE62C8 l, h5CFD72B3 l, hA0BE64C8 l, h5CFD72B3 l,
h64BFE930 l, h64BFE931 l, h8BE672F l, h5CFE6B2A l, h5CFE6B2A l, h5CFE6B2A l, h5CFE6B2A l, h5CFE6B2A l,
h5CFE6B2A l, h5CFE6B2A l, h5CFE6B2A l, h5CFE6B2A l, h5CFE6B2A l, h5CFE6B2A l, h5CFE6B2A l, h5CFE6B2A l,
h5CFE6B2A l, h5CFE6B2A l, h5CFE6B2A l, h68BFE931 l, h5CFE6B2A l, h5CFE6B2A l, h5CFE6B2A l, h5CFE6B2A l,
h5CFE6B2A l, h5CFE6B2A l, h5CFE6B2A l, h5CFE6B2A l, h5CFE6B2A l, h5CFE6B2A l, h5CFE6B2A l, h5CFE6B2A l,
h5CFE6B2A l, h5CFE6B2A l, h5CFE6B2A l, h5CFE6B2A l, h64BFE931 l, h5C7C0106 l, hF03E6532 l, hF43E6532 l,
h2DFE6601 l, h70BFE930 l, h5C3C0135 l, 0 l, h4 l, h2 l, h1 l, 0 l,
hFFFF7FFE l, 0 l,
freedict

\ ( toneOutput cyclesLeft currentStepIndexVector stepVector typeGainVector numTonesAddr -- )

lockdict create __genwave forthentry
$C_a_lxasm w, h18D  hFC  1- tuck - h9 lshift swap h1FF and or here W@ alignl h10 lshift or l,
hA0BF06C8 l, h5CFD72B3 l, hA0BF0AC8 l, h5CFD72B3 l, hA0BF08C8 l, h5CFD72B3 l, hA0BF0CC8 l, h5CFD72B3 l,
hA0BF04C8 l, h5CFD72B3 l, hA0BF02C8 l, h5CFD72B3 l, hA0BEFDF1 l, h80BEFD7F l, hF8BEFD7F l, hA0FF1600 l,
h8BF1383 l, h877F1200 l, h5C680154 l, hA0BEE385 l, h80BEE387 l, h8BF1971 l, hA0BEE384 l, h80BEE387 l,
h8BEFB71 l, hA0BEE386 l, h80BEE387 l, h8BEF971 l, hA0BEE57C l, h80BEE57D l, h83EE571 l, hA0BEE37C l,
h28FEE213 l, hA0BF158C l, h60FF19FF l, h28FF1410 l, h60FF1403 l, h877F1403 l, h5CEAD96A l, h877F1402 l,
h5CEAE16D l, h877F1401 l, h5CEAD362 l, h877F1400 l, h5CEAC359 l, hA0FEE400 l, h627F1801 l, h8096E571 l,
h2CFEE201 l, h28FF1801 l, h627F1801 l, h8096E571 l, h2CFEE201 l, h28FF1801 l, h627F1801 l, h8096E571 l,
h2CFEE201 l, h28FF1801 l, h627F1801 l, h8096E571 l, h2CFEE201 l, h28FF1801 l, h627F1801 l, h8096E571 l,
h2CFEE201 l, h28FF1801 l, h627F1801 l, h8096E571 l, h2CFEE201 l, h28FF1801 l, h627F1801 l, h8096E571 l,
h2CFEE201 l, h28FF1801 l, h627F1801 l, h8096E571 l, h2CFEE201 l, h28FF1801 l, h627F1801 l, h8096E571 l,
h80FEE480 l, h28FEE408 l, h80BF1772 l, h80FF0E04 l, h86FF1201 l, h5C54010F l, hA0FF0E00 l, h83F1781 l,
hA0BEE37E l, h84BEE3F1 l, h83EE382 l, h5C7C010A l, h5C7C0073 l, h613EE375 l, h623EE376 l, hA4B2E371 l,
h68BEE377 l, h2CFEE201 l, h4BEE371 l, hA496E371 l, h80BEE37B l, h5C7C0000 l, h613EE375 l, h623EE376 l,
hA4B2E371 l, h60BEE379 l, h2CFEE205 l, hA496E371 l, h80BEE37B l, h5C7C0000 l, h60BEE378 l, h2CFEE204 l,
h5C7C0000 l, h623EE376 l, hA0AAE37A l, hA0D6E200 l, h5C7C0000 l, 0 l, 0 l, 0 l,
0 l, h800 l, h1000 l, h7000 l, h1FFF l, h7FF l, h1FFFF l, h10000 l,
0 l, h5CE13BD l, 0 l, h716 l, 0 l, 0 l, 0 l, h1 l,
0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l,
0 l,
freedict

lockdict create __mixer forthentry
$C_a_lxasm w, h14E  hFC  1- tuck - h9 lshift swap h1FF and or here W@ alignl h10 lshift or l,
hA0BE98C8 l, h5CFD72B3 l, hA0BE86C8 l, h5CFD72B3 l, hA0BE84C8 l, h5CFD72B3 l, h83E8D43 l, hA0BE8942 l,
hA0FE8C00 l, h8BE8B44 l, h80FE8804 l, h80BE8D45 l, h8BE8B44 l, h80FE8804 l, h80BE8D45 l, h8BE8B44 l,
h80BE8D45 l, h28BE8D4B l, h8BE9B4C l, h4DBE8D47 l, h80CE9001 l, hA0FE8A00 l, h627E9A01 l, h80968B46 l,
h2CFE8C01 l, h28FE9A01 l, h627E9A01 l, h80968B46 l, h2CFE8C01 l, h28FE9A01 l, h627E9A01 l, h80968B46 l,
h2CFE8C01 l, h28FE9A01 l, h627E9A01 l, h80968B46 l, h2CFE8C01 l, h28FE9A01 l, h627E9A01 l, h80968B46 l,
h2CFE8C01 l, h28FE9A01 l, h627E9A01 l, h80968B46 l, h2CFE8C01 l, h28FE9A01 l, h627E9A01 l, h80968B46 l,
h2CFE8C01 l, h28FE9A01 l, h627E9A01 l, h80968B46 l, h2CFE8C01 l, h28FE9A01 l, h627E9A01 l, h80968B46 l,
h80FE8A80 l, h28FE8A08 l, hA0BE8D45 l, h87FE9201 l, h5C440102 l, hA0BE934A l, h877E91F4 l, h80C69601 l,
h84F29601 l, hA0FE9000 l, h44FE9608 l, h40FE9600 l, h5C7C0102 l, h5C7C0073 l, 0 l, 0 l,
0 l, 0 l, 0 l, hFFFF l, 0 l, h2710 l, h2710 l, 0 l,
0 l, 0 l,
freedict

lockdict create __simwave forthentry
$C_a_lxasm w, h109  hFC  1- tuck - h9 lshift swap h1FF and or here W@ alignl h10 lshift or l,
hA0BE0CC8 l, h5CFD72B3 l, h4BE1106 l, h28FE100C l, h60FE100F l, hA0FE0E01 l, h2CBE0F08 l, hA0BFE907 l,
h5C7C00FE l, h5C7C0073 l, 0 l, 0 l, 0 l,
freedict

\ set up the i2s 
: runI2s 
    d17 pinout d18 pinout d19 pinout 17 bitFrequency setHza
    d17 >m  d18 >m d19 >m toneOutput _i2s
;

\ ( n -- ) n - cog offset
: runGenWave
    4*
    toneOutput over + swap
    cyclesLeft over + swap
    currentStepIndexVector over cogArraySize u* + swap
    stepVector over cogArraySize u* + swap
    typeGainVector over cogArraySize u* + swap
    numTones +
    __genwave
;

\ set up wave simulator, can see the wave on logic analyzer
: runSimWave
    dira COG@ hFFFF or dira COG! toneSum __simwave
;

: runMixer
    toneOutput toneSum volume __mixer
;

: mix 
    begin
        toneOutput L@ 
        toneOutput 4+ L@ +
        toneOutput 4+ 4+ L@ +
        toneSum L! 
        0
    until
;  

: dd
    typeGainVector d64 dump
    stepVector d64 dump
    currentStepIndexVector d64 dump
;

: tmon 
    begin 
        toneOutput L@ . 
        toneOutput 4+ L@ . 
        toneOutput 4+ 4+ L@ . 
        toneSum L@ .
        cr esc? 
    until 
;

: cmon 
    begin 
        cyclesLeft L@ . 
        cyclesLeft 4+ L@ . 
        cyclesLeft 4+ 4+ L@ . 
        cr 1000 delms esc? 
    until 
;

c" runI2s" 0 cogx
c" 0 runGenWave" 1 cogx
c" 1 runGenWave" 2 cogx
c" runSimWave" 3 cogx
c" runMixer"  4 cogx



typeSin      d64   d400  d0 setTone 
typeTriangle d0    d500  d1 setTone 
typeTriangle d0    d600  d2 setTone 
typeTriangle d0    d700  d3 setTone 
typeTriangle d0    d800  d4 setTone 
typeTriangle d0    d900  d5 setTone 
typeTriangle d0    d1000 d6 setTone 
typeTriangle d0    d1100 d7 setTone 
typeTriangle d0    d1200 d8 setTone 
typeTriangle d0    d1300 d9 setTone 
d0 setVolume


\ test scenarios

typeSin      d64   d400  d0 setTone 
typeTriangle d0    d500  d1 setTone 
typeTriangle d0    d600  d2 setTone 
typeTriangle d0    d700  d3 setTone 
typeTriangle d0    d800  d4 setTone 
typeTriangle d0    d900  d5 setTone 
typeTriangle d0    d1000 d6 setTone 
typeTriangle d0    d1100 d7 setTone 
typeTriangle d0    d1200 d8 setTone 
typeTriangle d0    d1300 d9 setTone 
d256 setVolume


typeSin      d256   d400  d0 setTone 
typeTriangle d0    d500  d1 setTone 
typeTriangle d0    d600  d2 setTone 
typeTriangle d0    d700  d3 setTone 
typeTriangle d0    d800  d4 setTone 
typeTriangle d0    d900  d5 setTone 
typeTriangle d0    d1000 d6 setTone 
typeTriangle d0    d1100 d7 setTone 
typeTriangle d0    d1200 d8 setTone 
typeTriangle d0    d1300 d9 setTone 
d256 setVolume

typeSin      d256   d400  d0 setTone 
typeSquare   d128   d1200 d1 setTone 
typeTriangle d0    d600  d2 setTone 
typeTriangle d0    d700  d3 setTone 
typeTriangle d0    d800  d4 setTone 
typeTriangle d0    d900  d5 setTone 
typeTriangle d0    d1000 d6 setTone 
typeTriangle d0    d1100 d7 setTone 
typeTriangle d0    d1200 d8 setTone 
typeTriangle d0    d1300 d9 setTone 
d256 setVolume


typeSin      d64   d400  d0 setTone 
typeTriangle d0    d500  d1 setTone 
typeTriangle d0    d600  d2 setTone 
typeTriangle d0    d700  d3 setTone 
typeTriangle d0    d800  d4 setTone 
typeTriangle d0    d900  d5 setTone 
typeTriangle d0    d1000 d6 setTone 
typeTriangle d0    d1100 d7 setTone 
typeSin      d32   d1200 d8 setTone 
typeTriangle d0    d1300 d9 setTone 
d256 setVolume


typeSin      d64   d400  d0 setTone 
typeTriangle d0    d500  d1 setTone 
typeTriangle d0    d600  d2 setTone 
typeTriangle d0    d700  d3 setTone 
typeTriangle d64   d800  d4 setTone 
typeTriangle d0    d900  d5 setTone 
typeTriangle d0    d1000 d6 setTone 
typeTriangle d0    d1100 d7 setTone 
typeSquare   d0    d1200 d8 setTone 
typeTriangle d0    d1300 d9 setTone 
d256 setVolume




4 cogreset 1000 delms c" runMixer" 4 cogx

\ END TEST



\ set up variable sampling bins for wave generation





////////////// test 1 end













\ assembler source

\ _i2s ( clockMask lrMask dataOutMask dataAddr -- )  clockMask - input  lrMask,dataOutMask - outputs 
\   dataAddr - pointer to long, 16 bits for each channel left channel is the lo 16 bits signed values
build_BootOpt :rasm
	            mov     __dataAddr , $C_stTOS
	            spop
	            mov     __dataOutMask , $C_stTOS
	            spop
	            mov     __lrMask , $C_stTOS
	            spop
	            mov     __clockMask , $C_stTOS
                spop
                andn    outa , __dataOutMask
                andn    outa , __lrMask
__mainLoop
                rdlong  __currentData , __dataAddr
\ clock - 49
                jmpret  __bitOutRet , # __bitOut
\ max t = 55 clocks
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut

                or      outa , __lrMask

                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                andn    outa , __lrMask
\ clock - 22
                jmp     # __mainLoop
\ clock - 26

__bitOut
                waitpeq __clockMask , __clockMask
\ clock - 0 -- clock 55
                waitpne __clockMask , __clockMask
\ clock - 6
                shl     __currentData , # 1 wc
\ clock - 10
                muxc    outa , __dataOutMask
\ clock - 14
                jmp     __bitOutRet
\ clock - 18    

__dataAddr
                0
__dataOutMask
                4
__lrMask
                2
__clockMask
                1
__currentData
                0
__data
                hFFFF7FFE
__bitOutRet
                0

;asm _i2s


\ ( toneOutput cyclesLeft currentStepIndexVector stepVector typeGainVector numTonesAddr -- )
build_BootOpt :rasm
                mov     __numTones , $C_stTOS
                spop
                mov     __typeGainVector , $C_stTOS
                spop
                mov     __stepVector , $C_stTOS
                spop
                mov     __currentStepIndexVector , $C_stTOS
                spop
                mov     __cyclesLeft , $C_stTOS
                spop
                mov     __toneOutput , $C_stTOS
                spop
                mov     __time , cnt
                add     __time , __period
__mainLoop
                waitcnt __time , __period
                mov     __outSum , # 0
                rdlong  __toneLimit , __numTones
                cmp     __toneLimit , # 0           wc wz
    if_z        jmp     # __tonesDone
__toneLoop 
                mov     __r0 , __typeGainVector
                add     __r0 , __currentToneOffset 
                rdlong  __gain , __r0

                mov     __r0 , __stepVector
                add     __r0 , __currentToneOffset 
                rdlong  __step , __r0

                mov     __r0 , __currentStepIndexVector
                add     __r0 , __currentToneOffset 
                rdlong  __currentStepIndex , __r0

                mov     __r1 , __currentStepIndex
                add     __r1 , __step
                wrlong  __r1 , __r0

                mov     __r0 , __currentStepIndex
                shr     __r0 , # d19
                mov     __type , __gain
                and     __gain , # h1FF
                shr     __type , # d16
                and     __type , # 3

                cmp     __type , # 3                  wc wz
    if_e        jmpret  __sawRet , # __saw
                cmp     __type , # 2                  wc wz
    if_e        jmpret  __squareRet , # __square
                cmp     __type , # 1                  wc wz
    if_e        jmpret  __triangleRet , # __triangle
                cmp    __type , # 0                   wc wz
    if_e        jmpret  __sinRet ,  # __sin

                mov     __r1 , # 0

                test    __gain , # 1     wz
    if_nz       add     __r1 , __r0
                shl     __r0 , # 1
                shr     __gain , # 1
                test    __gain , # 1     wz
    if_nz       add     __r1 , __r0
                shl     __r0 , # 1
                shr     __gain , # 1
                test    __gain , # 1     wz
    if_nz       add     __r1 , __r0
                shl     __r0 , # 1
                shr     __gain , # 1
                test    __gain , # 1     wz
    if_nz       add     __r1 , __r0
                shl     __r0 , # 1
                shr     __gain , # 1
                test    __gain , # 1     wz
    if_nz       add     __r1 , __r0
                shl     __r0 , # 1
                shr     __gain , # 1
                test    __gain , # 1     wz
    if_nz       add     __r1 , __r0
                shl     __r0 , # 1
                shr     __gain , # 1
                test    __gain , # 1     wz
    if_nz       add     __r1 , __r0
                shl     __r0 , # 1
                shr     __gain , # 1
                test    __gain , # 1     wz
    if_nz       add     __r1 , __r0
                shl     __r0 , # 1
                shr     __gain , # 1
                test    __gain , # 1     wz
    if_nz       add     __r1 , __r0
                add     __r1 , # d128
                shr     __r1 , # 8

                add     __outSum , __r1

                add     __currentToneOffset , # 4

                sub     __toneLimit , # 1             wz
    if_nz       jmp    # __toneLoop

                mov     __currentToneOffset , # 0                
                wrlong  __outSum , __toneOutput
__tonesDone
                mov     __r0 , __time
                sub     __r0 , cnt               
                wrlong  __r0 , __cyclesLeft

                jmp     # __mainLoop

                jexit
__sin
                test    __r0 , __quad90 wc
                test    __r0 , __quad180 wz
    if_c        neg     __r0 , __r0
                or      __r0 , __sinTable
                shl     __r0 , # 1
                rdword  __r0 , __r0
    if_nz       neg     __r0 , __r0
                add     __r0 , __midValue
__sinRet
                ret
__triangle
                test    __r0 , __quad90 wc
                test    __r0 , __quad180 wz
    if_c        neg     __r0 , __r0
                and     __r0 , __angleMask
                shl     __r0 , # 5
    if_nz       neg     __r0 , __r0
                add     __r0 , __midValue
__triangleRet
                ret
__saw
                and     __r0 , __angleMask360
                shl     __r0 , # 4
__sawRet
                ret
__square
                test    __r0 , __quad180 wz
    if_z        mov     __r0 , __maxValue
    if_nz       mov     __r0 , # 0
__squareRet
                ret
__r0
                0
__r1
                0
__r2
                0
__r3
                0
__quad90
                h800 
__quad180
                h1000 
\ 0xE000 >> 1
__sinTable
                h7000
__angleMask360
                h1FFF
__angleMask
                h7FF
__maxValue
                h1FFFF 
__midValue
                h10000
__currentStepIndex
                0
__step
                d97391549
__time
                0
__period
                d1814
__debug
                0
__toneOutput
                0
__cyclesLeft
                0
__numTones
                1
__stepVector
                0
__typeGainVector
                0
__currentStepIndexVector
                0
__currentToneOffset 
                0
__toneNum
                0
__toneLimit
                0
__type
                0
__outSum
                0
__gain
                0
;asm __genwave  



\ ( toneAddrs outAddr volumeAddr --  ) 
build_BootOpt :rasm
                mov     __volumeAddr , $C_stTOS
                spop
                mov     __outAddr , $C_stTOS
                spop
                mov     __toneAddrs , $C_stTOS
                spop
__mainLoop
                wrlong  __value , __outAddr
                mov     __r0 ,  __toneAddrs
                mov     __value , # 0
                rdlong  __r1 , __r0
                add     __r0 , # d4
                add     __value , __r1
                rdlong  __r1 , __r0
                add     __r0 , # d4
                add     __value , __r1
                rdlong  __r1 , __r0
                add     __value , __r1
                shr     __value , __agcRightShift
                rdlong  __volume , __volumeAddr
 
                max     __value , __maxValue    wc
    if_nc       add     __agcCount , # 1

                mov     __r1 , # 0
                test    __volume , # 1     wz
    if_nz       add     __r1 , __value
                shl     __value , # 1
                shr     __volume , # 1
                test    __volume , # 1     wz
    if_nz       add     __r1 , __value
                shl     __value , # 1
                shr     __volume , # 1
                test    __volume , # 1     wz
    if_nz       add     __r1 , __value
                shl     __value , # 1
                shr     __volume , # 1
                test    __volume , # 1     wz
    if_nz       add     __r1 , __value
                shl     __value , # 1
                shr     __volume , # 1
                test    __volume , # 1     wz
    if_nz       add     __r1 , __value
                shl     __value , # 1
                shr     __volume , # 1
                test    __volume , # 1     wz
    if_nz       add     __r1 , __value
                shl     __value , # 1
                shr     __volume , # 1
                test    __volume , # 1     wz
    if_nz       add     __r1 , __value
                shl     __value , # 1
                shr     __volume , # 1
                test    __volume , # 1     wz
    if_nz       add     __r1 , __value
                shl     __value , # 1
                shr     __volume , # 1
                test    __volume , # 1     wz
    if_nz       add     __r1 , __value
                add     __r1 , # d128
                shr     __r1 , # 8
                mov     __value , __r1

                sub     __loopCount , # 1       wz wc
    if_a        jmp     # __mainLoop

                mov     __loopCount , __loopCountReset
                cmp     __agcCount , # d500 wz wc
    if_a        add     __agcRightShift , # 1
    if_b        sub     __agcRightShift , # 1
                mov     __agcCount , # 0

                maxs    __agcRightShift , # d8 
                mins    __agcRightShift , # 0
 
                jmp     # __mainLoop
                jexit
__toneAddrs
                0
__outAddr
                0
__r0
                0
__r1
                0       
__value
                0            
__maxValue
                hFFFF
__agcCount
                0
__loopCount
                d10000
__loopCountReset
                d10000
__agcRightShift
                0      
__volumeAddr
                0
__volume
                0
;asm __mixer





\ ( addrIn --  ) 
build_BootOpt :rasm
                mov     __addrIn , $C_stTOS
                spop
__mainLoop
                rdword  __value , __addrIn
                shr     __value , # d12
                and     __value , # d15
                mov     __r1 , # 1
                shl     __r1 , __value
                mov     outa , __r1
                jmp     # __mainLoop
                jexit
__addrIn
                0
__r1
                0            
__value
                0            
;asm __simwave



\ ( addr period --  ) pwm from addr
build_BootOpt :rasm
                mov     __period , $C_stTOS
                spop
                mov     __addr , $C_stTOS
                spop
                mov     __time , cnt
                add     __time , __period
__mainLoop
                rdword  __value , __addr
                shl     __value , # 6
                waitcnt __time , __period
                neg     phsa , __value
                jmp     # __mainLoop
                jexit
__value
                0                
__time
                0
__period
                0
__addr
                0
;asm __pwmout


\
\ 
\
\



\ ( value n -- m  ) 
build_BootOpt :rasm
                mov     __r0 , $C_stTOS
                spop
                mov     __r3 ,  $C_stTOS
                mov     __r2 , # 0
                mov     __r1 , # 1

                test    __r0 , __r1     wz
    if_nz       add     __r2 , __r3
                shl     __r1 , # 1
                shl     __r3 , # 1
                test    __r0 , __r1     wz
    if_nz       add     __r2 , __r3
                shl     __r1 , # 1
                shl     __r3 , # 1
                test    __r0 , __r1     wz
    if_nz       add     __r2 , __r3
                shl     __r1 , # 1
                shl     __r3 , # 1
                test    __r0 , __r1     wz
    if_nz       add     __r2 , __r3
                shl     __r1 , # 1
                shl     __r3 , # 1
                test    __r0 , __r1     wz
    if_nz       add     __r2 , __r3
                shl     __r1 , # 1
                shl     __r3 , # 1
                test    __r0 , __r1     wz
    if_nz       add     __r2 , __r3
                shl     __r1 , # 1
                shl     __r3 , # 1
                test    __r0 , __r1     wz
    if_nz       add     __r2 , __r3
                shl     __r1 , # 1
                shl     __r3 , # 1
                test    __r0 , __r1     wz
    if_nz       add     __r2 , __r3
                shl     __r1 , # 1
                shl     __r3 , # 1
                test    __r0 , __r1     wz
    if_nz       add     __r2 , __r3
                add     __r2 , # d128
                shr     __r2 , # 8
                mov      $C_stTOS , __r2
                jexit
__addrOfAddr
                0
__r0
                0            
__r1
                0            
__r2
                0            
__r3
                0
;asm __volume




\ END assembler source

\ END CURRENT TESTING


