\ CURRENT TESTING

\ pin0 - pin15 - simwave __toneOutput
\ pin 17 - bit clock for i2s (32 * LR ) - this is generated by a counter, and the i2s driver synch to this clock
\ pin 18 - i2s LR ( left right signal) 
\ pin 19 - data for i2s

\ dataOut  - low 16 its are left channel, high 16 bits are right channel

\ cog 0 - i2s driver,  clock A produces the bit clk 44100 sample rate
\ cog 1 - wave generator

d17 constant i2sBitClock
d18 constant i2sLrClock
d19 constant i2sData

\ 13 tableAddress bits for look up tables
d8192 constant tableLen

\ 32 bits - 13 bits = 19, shift when using a 32 bit unsigned value to index a table
d19 constant stepShift 

\ sample frequency
d44100 constant sampleFreq

\ clock cycles per sample
clkfreq sampleFreq / constant period

\ bit frequency for i2s
sampleFreq d32 * constant bitFrequency

\ (freq -- stepPerPeriod)
: freqToStep tableLen u* 1 stepShift lshift sampleFreq u*/ ;

\
\ ( -- t/f) if the esc key or CTL-E has been hit
[ifndef esc?
: esc?
	fkey?
	if 
		dup h1B = swap 5 = or 
	else 
		drop 0 
	then
	;
]

variable numTones
variable cyclesLeft
variable toneOutput
variable numTones
variable volume
9 constant maxNumTones
256 constant maxVolume
variable typeVector 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l,
variable gainVector 128 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l,
variable phaseVector 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l,
variable stepVector 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l,
variable currentStepIndexVector 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l,
variable volumeVector 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l,


\ 32 bit value for sound, hi 16 bits are right channel, lo 16 bits are left channel, each is a 16 bit signed value
variable  dataOut

: setNumTones maxNumTones 1+ min numTones L! ;
\ ( gain freq index -- )
: setTone maxNumTones min  4* swap freqToStep over stepVector + L! gainVector + L! ;
\ ( n -- ) n = 0-256 overall volume
: setVolume maxVolume min volume L! ;
: tmon begin cyclesLeft L@ . cr 1000 delms esc? until ;


\ __i2s ( clockMask lrMask dataOutMask dataAddr -- )
\ __genwave ( toneOutput cyclesLeft currentStepIndexVector stepVector phaseVector gainVector typeVector numTones period -- )
\ __simwave \ ( addrOfData --  ) 


lockdict create __i2s forthentry
$C_a_lxasm w, h135  hFC  1- tuck - h9 lshift swap h1FF and or here W@ alignl h10 lshift or l,
hA0BE5EC8 l, h5CFD72B3 l, hA0BE60C8 l, h5CFD72B3 l, hA0BE62C8 l, h5CFD72B3 l, hA0BE64C8 l, h5CFD72B3 l,
h64BFE930 l, h64BFE931 l, h8BE672F l, h5CFE692A l, h5CFE692A l, h5CFE692A l, h5CFE692A l, h5CFE692A l,
h5CFE692A l, h5CFE692A l, h5CFE692A l, h5CFE692A l, h5CFE692A l, h5CFE692A l, h5CFE692A l, h5CFE692A l,
h5CFE692A l, h5CFE692A l, h5CFE692A l, h68BFE931 l, h5CFE692A l, h5CFE692A l, h5CFE692A l, h5CFE692A l,
h5CFE692A l, h5CFE692A l, h5CFE692A l, h5CFE692A l, h5CFE692A l, h5CFE692A l, h5CFE692A l, h5CFE692A l,
h5CFE692A l, h5CFE692A l, h5CFE692A l, h5CFE692A l, h64BFE931 l, h5C7C0106 l, hF03E6532 l, hF43E6532 l,
h2DFE6601 l, h70BFE930 l, h5C3C0134 l, 0 l, h4 l, h2 l, h1 l, 0 l,
0 l,
freedict


lockdict create __genwave forthentry
$C_a_lxasm w, h19B  hFC  1- tuck - h9 lshift swap h1FF and or here W@ alignl h10 lshift or l,
hA0BF2EC8 l, h5CFD72B3 l, hA0BF1EC8 l, h5CFD72B3 l, hA0BF22C8 l, h5CFD72B3 l, hA0BF26C8 l, h5CFD72B3 l,
hA0BF20C8 l, h5CFD72B3 l, hA0BF24C8 l, h5CFD72B3 l, hA0BF1CC8 l, h5CFD72B3 l, hA0BF1AC8 l, h5CFD72B3 l,
hA0BF15F1 l, h80BF158B l, hF8BF158B l, hA0FF3200 l, h8BF2D8F l, h877F2C00 l, h5C680138 l, hA0BEFB93 l,
h80BEFB94 l, h8BF357D l, hA0BEFB91 l, h80BEFB94 l, h8BF317D l, hA0BEFB90 l, h80BEFB94 l, h8BF137D l,
hA0BEFB92 l, h80BEFB94 l, h8BF117D l, hA0BEFD88 l, h80BEFD89 l, h83EFD7D l, hA0BEFB88 l, h28FEFA13 l,
h80BF1189 l, h877F3003 l, h5CEAA14E l, h877F3002 l, h5CEAA951 l, h877F3001 l, h5CEA9B46 l, h877F3000 l,
h5CEA8B3D l, hA0BF017D l, hA0BEFB9A l, h5CFEF955 l, h80BF3380 l, h80FF2804 l, h80FF2A01 l, h873F2B96 l,
h5C700113 l, hA0FF2A00 l, hA0FF2800 l, h83F338D l, hA0BEFB8A l, h84BEFBF1 l, h83EFB8E l, h5C7C010E l,
h5C7C0073 l, h613EFB81 l, h623EFB82 l, hA4B2FB7D l, h68BEFB83 l, h2CFEFA01 l, h4BEFB7D l, hA496FB7D l,
h80BEFB87 l, h5C7C0000 l, h613EFB81 l, h623EFB82 l, hA4B2FB7D l, h60BEFB85 l, h2CFEFA05 l, hA496FB7D l,
h80BEFB87 l, h5C7C0000 l, h60BEFB84 l, h2CFEFA04 l, h5C7C0000 l, h623EFB82 l, hA0AAFB86 l, hA0D6FA00 l,
h5C7C0000 l, hA0FEFE00 l, hA0FEFC01 l, h623EFB7E l, h8096FF80 l, h2CFEFC01 l, h2CFF0001 l, h623EFB7E l,
h8096FF80 l, h2CFEFC01 l, h2CFF0001 l, h623EFB7E l, h8096FF80 l, h2CFEFC01 l, h2CFF0001 l, h623EFB7E l,
h8096FF80 l, h2CFEFC01 l, h2CFF0001 l, h623EFB7E l, h8096FF80 l, h2CFEFC01 l, h2CFF0001 l, h623EFB7E l,
h8096FF80 l, h2CFEFC01 l, h2CFF0001 l, h623EFB7E l, h8096FF80 l, h2CFEFC01 l, h2CFF0001 l, h623EFB7E l,
h8096FF80 l, h2CFEFC01 l, h2CFF0001 l, h623EFB7E l, h8096FF80 l, h80FEFE80 l, h28FEFE08 l, hA0BF017F l,
h5C7C0000 l, 0 l, 0 l, 0 l, 0 l, h800 l, h1000 l, h7000 l,
h1FFF l, h7FF l, h1FFFF l, h10000 l, 0 l, h5CE13BD l, 0 l, h716 l,
0 l, 0 l, 0 l, h1 l, 0 l, 0 l, 0 l, 0 l,
0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l,
freedict


lockdict create __simwave forthentry
$C_a_lxasm w, h10E  hFC  1- tuck - h9 lshift swap h1FF and or here W@ alignl h10 lshift or l,
hA0BE12C8 l, h5CFD72B3 l, h4BE1909 l, h28FE180C l, h60FE180F l, hA0FE1601 l, h2CBE170C l, hA0BE15F4 l,
h60BE150D l, h68BE150B l, hA0BFE90B l, h5C7C00FE l, h5C7C0073 l, 0 l, 0 l, 0 l,
0 l, hFFFF0000 l,
freedict

0 toneOutput L!
0 numTones L!
0 typeVector L!
0 currentStepIndexVector L!
0 stepVector L!
0 volume L!

\ set up the i2s 
: runI2s 
    i2sBitClock pinout i2sLrClock pinout i2sData pinout i2sBitClock bitFrequency setHza
    i2sBitClock >m i2sLrClock >m i2sData >m toneOutput __i2s
;
\ set up wave generator
: runGenWave
    toneOutput cyclesLeft
    currentStepIndexVector stepVector phaseVector gainVector typeVector
    numTones volume period __genwave
;
\ set up wave simulator, can see the wave on logic analyzer
: runSimWave
    dira COG@ hFFFF or dira COG! toneOutput __simwave
;

c" runI2s" 0 cogx
c" runGenWave" 1 cogx
c" runSimWave" 2 cogx


256 400 0 setTone 
1 numTones L!
64 volume L!

256 1200 1 setTone 
2 numTones L!
32 volume L!

256 400 0 setTone 
256 500 1 setTone 
256 600 2 setTone 
256 700 3 setTone 
256 800 4 setTone 
256 900 5 setTone 
256 1000 6 setTone 
256 1100 7 setTone 
256 1200 8 setTone 
256 1300 9 setTone 


10 numTones L!

: mn begin 
    toneOutput L@ . cr
    esc? until
    ;





////////////// test 1 end




\ assembler source

\ __i2s ( clockMask lrMask dataOutMask dataAddr -- ) 
\       clockMask - input  lrMask,dataOutMask - outputs   dataAddr - pointer to long 16 bits for each channel
\       left channel is the lo 16 bits, right channel is hi 16 bits, each is a 16 bit signed integer
build_BootOpt :rasm
	            mov     __dataAddr , $C_stTOS
	            spop
	            mov     __dataOutMask , $C_stTOS
	            spop
	            mov     __lrMask , $C_stTOS
	            spop
	            mov     __clockMask , $C_stTOS
                spop
                andn    outa , __dataOutMask
                andn    outa , __lrMask
__mainLoop
                rdlong  __currentData , __dataAddr
\ clock - 49
                jmpret  __bitOutRet , # __bitOut
\ max t = 55 clocks
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut

                or      outa , __lrMask

                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                andn    outa , __lrMask
\ clock - 22
                jmp     # __mainLoop
\ clock - 26

__bitOut
                waitpeq __clockMask , __clockMask
\ clock - 0 -- clock 55
                waitpne __clockMask , __clockMask
\ clock - 6
                shl     __currentData , # 1 wc
\ clock - 10
                muxc    outa , __dataOutMask
\ clock - 14
                jmp     __bitOutRet
\ clock - 18    

__dataAddr
                0
__dataOutMask
                4
__lrMask
                2
__clockMask
                1
__currentData
                0
__bitOutRet
                0
;asm __i2s



\ ( toneOutput cyclesLeft currentStepIndexVector stepVector phaseVector gainVector typeVector numTonesAddr volumeAddr period -- )
build_BootOpt :rasm
                mov     __period , $C_stTOS
                spop
                mov     __volumeAddr , $C_stTOS
                spop
                mov     __numTones , $C_stTOS
                spop
                mov     __typeVector , $C_stTOS
                spop
                mov     __gainVector , $C_stTOS
                spop
                mov     __phaseVector , $C_stTOS
                spop
                mov     __stepVector , $C_stTOS
                spop
                mov     __currentStepIndexVector , $C_stTOS
                spop
                mov     __cyclesLeft , $C_stTOS
                spop
                mov     __toneOutput , $C_stTOS
                spop
                mov     __time , cnt
                add     __time , __period
__mainLoop
                waitcnt __time , __period
                mov     __r3 , # 0
                rdlong  __toneLimit , __numTones
                cmp     __toneLimit , # 0           wc wz
    if_z        jmp     # __tonesDone
__toneLoop 
                mov     __r0 , __stepVector
                add     __r0 , __currentToneOffset 
                rdlong  __step , __r0

                mov     __r0 , __currentStepIndexVector
                add     __r0 , __currentToneOffset 
                rdlong  __currentStepIndex , __r0

                mov     __r1 , __currentStepIndex
                add     __r1 , __step
                wrlong  __r1 , __r0

                mov     __r0 , __currentStepIndex
                shr     __r0 , # d19

                jmpret  __sinRet ,  # __sin
                add     __r3 , __r0

                add     __currentToneOffset , # 4
                add     __toneNum , # 1
                cmp     __toneNum , __toneLimit      wc wz
    if_b        jmp    # __toneLoop

                mov     __toneNum , # 0            
                mov     __currentToneOffset , # 0 
                rdlong  __r0 , __volumeAddr
                jmpret  __applyVolumeRet ,  # __applyVolume

                max     __r3 , __lomask
               
                wrlong  __r3 , __toneOutput
__tonesDone
                mov     __r0 , __time
                sub     __r0 , cnt               
                wrlong  __r0 , __cyclesLeft

                jmp     # __mainLoop

                jexit
__sin
                test    __r0 , __quad90 wc
                test    __r0 , __quad180 wz
    if_c        neg     __r0 , __r0
                or      __r0 , __sinTable
                shl     __r0 , # 1
                rdword  __r0 , __r0
    if_nz       neg     __r0 , __r0
                add     __r0 , __midValue
__sinRet
                ret
__triangle
                test    __r0 , __quad90 wc
                test    __r0 , __quad180 wz
    if_c        neg     __r0 , __r0
                and     __r0 , __angleMask
                shl     __r0 , # 5
    if_nz       neg     __r0 , __r0
                add     __r0 , __midValue
__triangleRet
                ret
__saw
                and     __r0 , __angleMask360
                shl     __r0 , # 4
__sawRet
                ret
__square
                test    __r0 , __quad180 wz
    if_z        mov     __r0 , __maxValue
    if_nz       mov     __r0 , # 0
__squareRet
                ret
\ r0 volume 0 - 256
\ r3 value
__applyVolume
                mov     __r2 , # 0
                mov     __r1 , # 1

                test    __r0 , __r1     wz
    if_nz       add     __r2 , __r3
                shl     __r1 , # 1
                shl     __r3 , # 1
                test    __r0 , __r1     wz
    if_nz       add     __r2 , __r3
                shl     __r1 , # 1
                shl     __r3 , # 1
                test    __r0 , __r1     wz
    if_nz       add     __r2 , __r3
                shl     __r1 , # 1
                shl     __r3 , # 1
                test    __r0 , __r1     wz
    if_nz       add     __r2 , __r3
                shl     __r1 , # 1
                shl     __r3 , # 1
                test    __r0 , __r1     wz
    if_nz       add     __r2 , __r3
                shl     __r1 , # 1
                shl     __r3 , # 1
                test    __r0 , __r1     wz
    if_nz       add     __r2 , __r3
                shl     __r1 , # 1
                shl     __r3 , # 1
                test    __r0 , __r1     wz
    if_nz       add     __r2 , __r3
                shl     __r1 , # 1
                shl     __r3 , # 1
                test    __r0 , __r1     wz
    if_nz       add     __r2 , __r3
                shl     __r1 , # 1
                shl     __r3 , # 1
                test    __r0 , __r1     wz
    if_nz       add     __r2 , __r3
                add     __r2 , # d128
                shr     __r2 , # 8
                mov     __r3 , __r2
__applyVolumeRet
                ret
__r0
                0
__r1
                0
__r2
                0
__r3
                0
__lomask
                hFFFF
__himask
                hFFFF0000
__type
                0
__quad90
                h800 
__quad180
                h1000 
\ 0xE000 >> 1
__sinTable
                h7000
__angleMask360
                h1FFF
__angleMask
                h7FF
__maxValue
                h1FFFF 
__midValue
                h10000
__debug
                0
__output
                0
__att 
                0
__currentStepIndex
                0
__step
                0
__time
                0
__period
                0
__debug
                0
__toneOutput
                0
__cyclesLeft
                0
__numTones
                0
__phaseVector
                0
__stepVector
                0
__typeVector
                0
__currentStepIndexVector
                0
__gainVector
                0
__currentToneOffset 
                0
__toneNum
                0
__toneLimit
                0
__volumeAddr
                0
;asm __genwave


\ ( addrIn --  ) 
build_BootOpt :rasm
                mov     __addrIn , $C_stTOS
                spop
__mainLoop
                rdword  __value , __addrIn
                shr     __value , # d12
                and     __value , # d15
                mov     __r1 , # 1
                shl     __r1 , __value
                mov     __r0 , outa
                and     __r0 , __himask 
                or      __r0 , __r1
                mov     outa , __r1
                jmp     # __mainLoop
                jexit
__addrIn
                0
__r0
                0            
__r1
                0            
__value
                0            
__himask
                hFFFF0000
;asm __simwave



\ ( addrIn addrOut addrOutSigned addrAgcPeriod --  ) 
build_BootOpt :rasm
                mov     __addrOutSigned , $C_stTOS
                spop
                mov     __addrOut , $C_stTOS
                spop
                mov     __addrIn , $C_stTOS
                spop
__mainLoop
                rdlong  __value , __addrIn
                mov     __r3 , __value
                shr     __value , # d12
                and     __value , # d15
                mov     __r1 , # 1
                shl     __r1 , __value
                mov     __r0 , outa
                and     __r0 , __himask 
                or      __r0 , __r1
                mov     outa , __r1
                jmp     # __mainLoop
                jexit

\ r0 volume 0 - 256
\ r3 value
__applyVolume
                mov     __r2 , # 0
                mov     __r1 , # 1

                test    __r0 , __r1     wz
    if_nz       add     __r2 , __r3
                shl     __r1 , # 1
                shl     __r3 , # 1
                test    __r0 , __r1     wz
    if_nz       add     __r2 , __r3
                shl     __r1 , # 1
                shl     __r3 , # 1
                test    __r0 , __r1     wz
    if_nz       add     __r2 , __r3
                shl     __r1 , # 1
                shl     __r3 , # 1
                test    __r0 , __r1     wz
    if_nz       add     __r2 , __r3
                shl     __r1 , # 1
                shl     __r3 , # 1
                test    __r0 , __r1     wz
    if_nz       add     __r2 , __r3
                shl     __r1 , # 1
                shl     __r3 , # 1
                test    __r0 , __r1     wz
    if_nz       add     __r2 , __r3
                shl     __r1 , # 1
                shl     __r3 , # 1
                test    __r0 , __r1     wz
    if_nz       add     __r2 , __r3
                shl     __r1 , # 1
                shl     __r3 , # 1
                test    __r0 , __r1     wz
    if_nz       add     __r2 , __r3
                shl     __r1 , # 1
                shl     __r3 , # 1
                test    __r0 , __r1     wz
    if_nz       add     __r2 , __r3
                add     __r2 , # d128
                shr     __r2 , # 8
                mov     __r3 , __r2
__applyVolumeRet
                ret

__addrIn
                0
__addrOut
                0
__addrSigned
                0
__r0
                0            
__r1
                0            
__r2
                0            
__r3
                0            
__value
                0      
__max
                hFFFF      
;asm __agc





\ END assembler source

\ END CURRENT TESTING




\ -----------------------------------------------------------------------------------------------20260330_160500


\ CURRENT TESTING

\ pin0 - pin15 - simwave __toneOutput
\ pin 17 - bit clock for i2s (32 * LR ) - this is generated by a counter, and the i2s driver synch to this clock
\ pin 18 - i2s LR ( left right signal)
\ pin 19 - data for i2s

\ dataOut  - low 16 its are left channel, high 16 bits are right channel

\ cog 0 - i2s driver,  clock A produces the bit clk 44100 sample rate
\ cog 1 - wave generator

d17 constant i2sBitClock
d18 constant i2sLrClock
d19 constant i2sData

\ 13 tableAddress bits for look up tables
d8192 constant tableLen

\ 32 bits - 13 bits = 19, shift when using a 32 bit unsigned value to index a table
d19 constant stepShift 

\ sample frequency
d44100 constant sampleFreq

\ clock cycles per sample
clkfreq sampleFreq / constant period

\ bit frequency for i2s
sampleFreq d32 * constant bitFrequency

\ (freq -- stepPerPeriod)
: freqToStep tableLen u* 1 stepShift lshift sampleFreq u*/ ;

\
\ ( -- t/f) if the esc key or CTL-E has been hit
[ifndef esc?
: esc?
	fkey?
	if 
		dup h1B = swap 5 = or 
	else 
		drop 0 
	then
	;
]

variable numTones
variable cyclesLeft
variable toneOutput
variable numTones
variable volume
9 constant maxNumTones
256 constant maxVolume
variable typeVector 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l,
variable gainVector 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l,
variable phaseVector 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l,
variable stepVector 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l,
variable currentStepIndexVector 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l,
variable volumeVector 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l,


\ 32 bit value for sound, hi 16 bits are right channel, lo 16 bits are left channel, each is a 16 bit signed value
variable  dataOut

: setNumTones maxNumTones 1+ min numTones L! ;
\ ( volume freq index -- )
: setTone maxNumTones min  4* swap freqToStep over stepVector + L! volumeVector + L! ;
\ ( n -- ) n = 0-256 overall volume
: setVolume maxVolume min volume L! ;
: tmon begin cyclesLeft L@ . cr 1000 delms esc? until ;


\ __i2s ( clockMask lrMask dataOutMask dataAddr -- )
\ __genwave ( toneOutput cyclesLeft currentStepIndexVector stepVector phaseVector gainVector typeVector numTones -- )
\ __simwave \ ( addrOfData --  ) 


lockdict create __i2s forthentry
$C_a_lxasm w, h135  hFC  1- tuck - h9 lshift swap h1FF and or here W@ alignl h10 lshift or l,
hA0BE5EC8 l, h5CFD72B3 l, hA0BE60C8 l, h5CFD72B3 l, hA0BE62C8 l, h5CFD72B3 l, hA0BE64C8 l, h5CFD72B3 l,
h64BFE930 l, h64BFE931 l, h8BE672F l, h5CFE692A l, h5CFE692A l, h5CFE692A l, h5CFE692A l, h5CFE692A l,
h5CFE692A l, h5CFE692A l, h5CFE692A l, h5CFE692A l, h5CFE692A l, h5CFE692A l, h5CFE692A l, h5CFE692A l,
h5CFE692A l, h5CFE692A l, h5CFE692A l, h68BFE931 l, h5CFE692A l, h5CFE692A l, h5CFE692A l, h5CFE692A l,
h5CFE692A l, h5CFE692A l, h5CFE692A l, h5CFE692A l, h5CFE692A l, h5CFE692A l, h5CFE692A l, h5CFE692A l,
h5CFE692A l, h5CFE692A l, h5CFE692A l, h5CFE692A l, h64BFE931 l, h5C7C0106 l, hF03E6532 l, hF43E6532 l,
h2DFE6601 l, h70BFE930 l, h5C3C0134 l, 0 l, h4 l, h2 l, h1 l, 0 l,
0 l,
freedict


lockdict create __genwave forthentry
$C_a_lxasm w, h193  hFC  1- tuck - h9 lshift swap h1FF and or here W@ alignl h10 lshift or l,
hA0BF24C8 l, h5CFD72B3 l, hA0BF12C8 l, h5CFD72B3 l, hA0BF18C8 l, h5CFD72B3 l, hA0BF1CC8 l, h5CFD72B3 l,
hA0BF14C8 l, h5CFD72B3 l, hA0BF16C8 l, h5CFD72B3 l, hA0BF1AC8 l, h5CFD72B3 l, hA0BF10C8 l, h5CFD72B3 l,
hA0BF0EC8 l, h5CFD72B3 l, hA0BF09F1 l, h80BF0985 l, hF8BF0985 l, hA0FEE800 l, h8BF2389 l, h877F2200 l,
h5C68012C l, hA0BEE38B l, h80BEE38F l, h8BF0771 l, hA0BEE38D l, h80BEE38F l, h8BF0571 l, hA0BEE582 l,
h80BEE583 l, h83EE571 l, hA0BEE382 l, h28FEE213 l, h5CFE7331 l, h80BEE971 l, h80FF1E04 l, h80FF2001 l,
h873F2191 l, h5C700115 l, hA0FF2000 l, hA0FF1E00 l, h8BEE392 l, h5CFEE149 l, h4CBEE975 l, h83EE987 l,
hA0BEE384 l, h84BEE3F1 l, h83EE388 l, h5C7C0110 l, h5C7C0073 l, h613EE378 l, h623EE379 l, hA4B2E371 l,
h68BEE37A l, h2CFEE201 l, h4BEE371 l, hA496E371 l, h80BEE37E l, h5C7C0000 l, h613EE378 l, h623EE379 l,
hA4B2E371 l, h60BEE37C l, h2CFEE205 l, hA496E371 l, h80BEE37E l, h5C7C0000 l, h60BEE37B l, h2CFEE204 l,
h5C7C0000 l, h623EE379 l, hA0AAE37D l, hA0D6E200 l, h5C7C0000 l, hA0FEE600 l, hA0FEE401 l, h623EE372 l,
h8096E774 l, h2CFEE401 l, h2CFEE801 l, h623EE372 l, h8096E774 l, h2CFEE401 l, h2CFEE801 l, h623EE372 l,
h8096E774 l, h2CFEE401 l, h2CFEE801 l, h623EE372 l, h8096E774 l, h2CFEE401 l, h2CFEE801 l, h623EE372 l,
h8096E774 l, h2CFEE401 l, h2CFEE801 l, h623EE372 l, h8096E774 l, h2CFEE401 l, h2CFEE801 l, h623EE372 l,
h8096E774 l, h2CFEE401 l, h2CFEE801 l, h623EE372 l, h8096E774 l, h2CFEE401 l, h2CFEE801 l, h623EE372 l,
h8096E774 l, h80FEE680 l, h28FEE608 l, hA0BEE973 l, h5C7C0000 l, 0 l, 0 l, 0 l,
0 l, hFFFF l, hFFFF0000 l, 0 l, h800 l, h1000 l, h7000 l, h1FFF l,
h7FF l, h1FFFF l, h10000 l, 0 l, 0 l, 0 l, 0 l, h5CE13BD l,
0 l, h716 l, 0 l, 0 l, 0 l, h1 l, 0 l, 0 l,
0 l, 0 l, 0 l, 0 l, 0 l, 0 l, 0 l,
freedict


lockdict create __simwave forthentry
$C_a_lxasm w, h10E  hFC  1- tuck - h9 lshift swap h1FF and or here W@ alignl h10 lshift or l,
hA0BE12C8 l, h5CFD72B3 l, h4BE1909 l, h28FE180C l, h60FE180F l, hA0FE1601 l, h2CBE170C l, hA0BE15F4 l,
h60BE150D l, h68BE150B l, hA0BFE90B l, h5C7C00FE l, h5C7C0073 l, 0 l, 0 l, 0 l,
0 l, hFFFF0000 l,
freedict

0 toneOutput L!
0 numTones L!
0 typeVector L!
0 currentStepIndexVector L!
0 stepVector L!
0 volume L!

\ set up the i2s 
: runI2s 
    i2sBitClock pinout i2sLrClock pinout i2sData pinout i2sBitClock bitFrequency setHza
    i2sBitClock >m i2sLrClock >m i2sData >m toneOutput __i2s
;
\ set up wave generator
: runGenWave
    toneOutput cyclesLeft
    currentStepIndexVector stepVector phaseVector gainVector typeVector
    numTones volume __genwave
;
\ set up wave simulator, can see the wave on logic analyzer
: runSimWave
    dira COG@ hFFFF or dira COG! toneOutput __simwave
;

c" runI2s" 0 cogx
c" runGenWave" 1 cogx
c" runSimWave" 2 cogx


256 400 0 setTone 
1 numTones L!
64 volume L!

256 1200 1 setTone 
2 numTones L!
32 volume L!

256 400 0 setTone 
256 500 1 setTone 
256 600 2 setTone 
256 700 3 setTone 
256 800 4 setTone 
256 900 5 setTone 
256 1000 6 setTone 
256 1100 7 setTone 
256 1200 8 setTone 
256 1300 9 setTone 


10 numTones L!

: mn begin 
    toneOutput L@ . cr
    esc? until
    ;





////////////// test 1 end




\ assembler source

\ __i2s ( clockMask lrMask dataOutMask dataAddr -- ) 
\       clockMask - input  lrMask,dataOutMask - outputs   dataAddr - pointer to long 16 bits for each channel
\       left channel is the lo 16 bits, right channel is hi 16 bits, each is a 16 bit signed integer
build_BootOpt :rasm
	            mov     __dataAddr , $C_stTOS
	            spop
	            mov     __dataOutMask , $C_stTOS
	            spop
	            mov     __lrMask , $C_stTOS
	            spop
	            mov     __clockMask , $C_stTOS
                spop
                andn    outa , __dataOutMask
                andn    outa , __lrMask
__mainLoop
                rdlong  __currentData , __dataAddr
\ clock - 49
                jmpret  __bitOutRet , # __bitOut
\ max t = 55 clocks
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut

                or      outa , __lrMask

                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                jmpret  __bitOutRet , # __bitOut
                andn    outa , __lrMask
\ clock - 22
                jmp     # __mainLoop
\ clock - 26

__bitOut
                waitpeq __clockMask , __clockMask
\ clock - 0 -- clock 55
                waitpne __clockMask , __clockMask
\ clock - 6
                shl     __currentData , # 1 wc
\ clock - 10
                muxc    outa , __dataOutMask
\ clock - 14
                jmp     __bitOutRet
\ clock - 18    

__dataAddr
                0
__dataOutMask
                4
__lrMask
                2
__clockMask
                1
__currentData
                0
__bitOutRet
                0

;asm __i2s



\ ( toneOutput cyclesLeft currentStepIndexVector stepVector phaseVector gainVector typeVector numTonesAddr volumeAddr -- )
build_BootOpt :rasm
                mov     __volumeAddr , $C_stTOS
                spop
                mov     __numTones , $C_stTOS
                spop
                mov     __typeVector , $C_stTOS
                spop
                mov     __gainVector , $C_stTOS
                spop
                mov     __phaseVector , $C_stTOS
                spop
                mov     __stepVector , $C_stTOS
                spop
                mov     __currentStepIndexVector , $C_stTOS
                spop
                mov     __cyclesLeft , $C_stTOS
                spop
                mov     __toneOutput , $C_stTOS
                spop
                mov     __time , cnt
                add     __time , __period
__mainLoop
                waitcnt __time , __period
                mov     __r3 , # 0
                rdlong  __toneLimit , __numTones
                cmp     __toneLimit , # 0           wc wz
    if_z        jmp     # __tonesDone
__toneLoop 
                mov     __r0 , __stepVector
                add     __r0 , __currentToneOffset 
                rdlong  __step , __r0

                mov     __r0 , __currentStepIndexVector
                add     __r0 , __currentToneOffset 
                rdlong  __currentStepIndex , __r0

                mov     __r1 , __currentStepIndex
                add     __r1 , __step
                wrlong  __r1 , __r0

                mov     __r0 , __currentStepIndex
                shr     __r0 , # d19

                jmpret  __sinRet ,  # __sin
                add     __r3 , __r0

                add     __currentToneOffset , # 4
                add     __toneNum , # 1
                cmp     __toneNum , __toneLimit      wc wz
    if_b        jmp    # __toneLoop

                mov     __toneNum , # 0            
                mov     __currentToneOffset , # 0 
                rdlong  __r0 , __volumeAddr
                jmpret  __applyVolumeRet ,  # __applyVolume

                max     __r3 , __lomask
               
                wrlong  __r3 , __toneOutput
__tonesDone
                mov     __r0 , __time
                sub     __r0 , cnt               
                wrlong  __r0 , __cyclesLeft

                jmp     # __mainLoop

                jexit
__sin
                test    __r0 , __quad90 wc
                test    __r0 , __quad180 wz
    if_c        neg     __r0 , __r0
                or      __r0 , __sinTable
                shl     __r0 , # 1
                rdword  __r0 , __r0
    if_nz       neg     __r0 , __r0
                add     __r0 , __midValue
__sinRet
                ret
__triangle
                test    __r0 , __quad90 wc
                test    __r0 , __quad180 wz
    if_c        neg     __r0 , __r0
                and     __r0 , __angleMask
                shl     __r0 , # 5
    if_nz       neg     __r0 , __r0
                add     __r0 , __midValue
__triangleRet
                ret
__saw
                and     __r0 , __angleMask360
                shl     __r0 , # 4
__sawRet
                ret
__square
                test    __r0 , __quad180 wz
    if_z        mov     __r0 , __maxValue
    if_nz       mov     __r0 , # 0
__squareRet
                ret
\ r0 volume 0 - 256
\ r3 value
__applyVolume
                mov     __r2 , # 0
                mov     __r1 , # 1

                test    __r0 , __r1     wz
    if_nz       add     __r2 , __r3
                shl     __r1 , # 1
                shl     __r3 , # 1
                test    __r0 , __r1     wz
    if_nz       add     __r2 , __r3
                shl     __r1 , # 1
                shl     __r3 , # 1
                test    __r0 , __r1     wz
    if_nz       add     __r2 , __r3
                shl     __r1 , # 1
                shl     __r3 , # 1
                test    __r0 , __r1     wz
    if_nz       add     __r2 , __r3
                shl     __r1 , # 1
                shl     __r3 , # 1
                test    __r0 , __r1     wz
    if_nz       add     __r2 , __r3
                shl     __r1 , # 1
                shl     __r3 , # 1
                test    __r0 , __r1     wz
    if_nz       add     __r2 , __r3
                shl     __r1 , # 1
                shl     __r3 , # 1
                test    __r0 , __r1     wz
    if_nz       add     __r2 , __r3
                shl     __r1 , # 1
                shl     __r3 , # 1
                test    __r0 , __r1     wz
    if_nz       add     __r2 , __r3
                shl     __r1 , # 1
                shl     __r3 , # 1
                test    __r0 , __r1     wz
    if_nz       add     __r2 , __r3
                add     __r2 , # d128
                shr     __r2 , # 8
                mov     __r3 , __r2
__applyVolumeRet
                ret
__r0
                0
__r1
                0
__r2
                0
__r3
                0
__lomask
                hFFFF
__himask
                hFFFF0000
__type
                0
__quad90
                h800 
__quad180
                h1000 
\ 0xE000 >> 1
__sinTable
                h7000
__angleMask360
                h1FFF
__angleMask
                h7FF
__maxValue
                h1FFFF 
__midValue
                h10000
__debug
                0
__output
                0
__att 
                0
__currentStepIndex
                0
__step
                d97391549
__time
                0
__period
                d1814
__debug
                0
__toneOutput
                0
__cyclesLeft
                0
__numTones
                1
__phaseVector
                0
__stepVector
                0
__typeVector
                0
__currentStepIndexVector
                0
__gainVector
                0
__currentToneOffset 
                0
__toneNum
                0
__toneLimit
                0
__volumeAddr
                0
;asm __genwave


\ ( addrIn --  ) 
build_BootOpt :rasm
                mov     __addrIn , $C_stTOS
                spop
__mainLoop
                rdword  __value , __addrIn
                shr     __value , # d12
                and     __value , # d15
                mov     __r1 , # 1
                shl     __r1 , __value
                mov     __r0 , outa
                and     __r0 , __himask 
                or      __r0 , __r1
                mov     outa , __r1
                jmp     # __mainLoop
                jexit
__addrIn
                0
__r0
                0            
__r1
                0            
__value
                0            
__himask
                hFFFF0000
;asm __simwave




\ END assembler source

\ END CURRENT TESTING

